import type { Trip, Booking, Inquiry, MediaItem, DashboardStats, SiteSettings, ItineraryDay, FAQ } from "@/types";

export const mockTrips: Trip[] = [
  {
    id: "1",
    title: "Manali Kasol Amritsar Backpacking Trip",
    slug: "manali-kasol-amritsar-adventure-trip",
    description: "Get ready for an unforgettable journey through Northern India! Explore the cultural richness at Wagah Border and the serene beauty of the Golden Temple in Amritsar. Venture to Kasol for riverside camping, visit Manikaran Gurudwara, trek to Chalal village. Experience the Bijli Mahadev trek, explore Manali attractions like Hadimba Devi Temple, Jogini Waterfall and Vashisht Hot Springs. Traverse the Atal Tunnel and explore Solang Valley. Head to Kullu for exciting rafting adventures.",
    price: 11999,
    location: "Manali, Kasol & Amritsar",
    duration: "8 Nights 9 Days",
    category: "Backpacking",
    images: [
      "https://vl-prod-static.b-cdn.net/system/images/000/888/076/6f012c2f939c45fd491d86b3d33b0cbb/x540gt/IMG_3309.jpg",
      "https://vl-prod-static.b-cdn.net/system/images/000/787/633/7dba267328e361ea13ef20b042c6f62f/original/Untitled_design__20_.jpg",
      "https://vl-prod-static.b-cdn.net/system/images/000/787/631/0bb3888fc4691faec634a98da33a1830/original/Untitled_design__22_.jpg",
    ],
    itinerary: [
      { day: 1, title: "Departure from Gujarat", description: "Board the bus from Ahmedabad/Surat. Overnight journey towards Amritsar.", photos: [] },
      { day: 2, title: "Arrival in Amritsar", description: "Visit Golden Temple, Jallianwala Bagh, and enjoy Amritsari street food. Evening Wagah Border ceremony.", photos: ["https://vl-prod-static.b-cdn.net/system/images/000/787/633/7dba267328e361ea13ef20b042c6f62f/original/Untitled_design__20_.jpg"] },
      { day: 3, title: "Amritsar to Kasol", description: "Scenic drive from Amritsar to Kasol through the Parvati Valley.", photos: [] },
      { day: 4, title: "Kasol Exploration", description: "Trek to Chalal village, visit Manikaran Gurudwara and hot springs. Riverside camping.", photos: [] },
      { day: 5, title: "Kasol to Manali", description: "Drive to Manali. Visit Hadimba Devi Temple and Old Manali market.", photos: [] },
      { day: 6, title: "Manali Sightseeing", description: "Bijli Mahadev Trek, Jogini Waterfall, Vashisht Hot Springs.", photos: ["https://vl-prod-static.b-cdn.net/system/images/000/888/076/6f012c2f939c45fd491d86b3d33b0cbb/x540gt/IMG_3309.jpg"] },
      { day: 7, title: "Solang Valley & Atal Tunnel", description: "Visit Solang Valley for adventure activities. Drive through the Atal Tunnel.", photos: [] },
      { day: 8, title: "Kullu Rafting & Departure", description: "Morning river rafting in Kullu. Begin return journey.", photos: [] },
      { day: 9, title: "Arrival Back", description: "Arrive back in Gujarat with unforgettable memories.", photos: [] },
    ],
    heroImage: "",
    highlights: ["Guided tours", "Scenic views", "Group activities"],
    inclusions: ["Accommodation", "Meals (Breakfast & Dinner)", "Transport", "Sightseeing", "Trip captain"],
    exclusions: ["Personal expenses", "Travel insurance", "Entry fees (if any)", "Anything not mentioned in inclusions"],
    faqs: [
      { question: "What is the age limit?", answer: "This trip is suitable for ages 12-35." },
      { question: "Is food included?", answer: "Yes, breakfast and dinner are included." },
      { question: "What about safety?", answer: "We have trained trip captains and first-aid kits on every trip." },
    ],
    status: "published",
    createdAt: "2024-01-15",
    updatedAt: "2024-03-01",
  },
  {
    id: "2",
    title: "Manali Kasol Amritsar Backpacking Trip (Summer 2026)",
    slug: "manali-kasol-amritsar-trip-summer-2026",
    description: "Summer edition of our most popular backpacking trip! Experience the best of Northern India — Amritsar's Golden Temple, Kasol's riverside vibes, Manali's mountain charm, and Kullu rafting. Perfect for ages 12-35 who love adventure and making new friends on the road.",
    price: 11999,
    location: "Ambli, Gujarat → North India",
    duration: "8 Nights 9 Days",
    category: "Backpacking",
    images: [
      "https://vl-prod-static.b-cdn.net/system/images/000/748/614/9b56160b1abe219a402c11001702ae24/x540gt/IMG_3398.JPG",
    ],
    itinerary: [
      { day: 1, title: "Departure from Gujarat", description: "Pickup from Ambli, Gujarat. Overnight journey.", photos: [] },
      { day: 2, title: "Amritsar – Golden Temple & Wagah", description: "Explore the Golden Temple and attend the Wagah Border ceremony.", photos: [] },
      { day: 3, title: "Travel to Kasol", description: "Scenic drive through Punjab and Himachal to Kasol.", photos: [] },
      { day: 4, title: "Kasol & Kheerganga Trek", description: "Trek to Kheerganga, enjoy hot springs and mountain views.", photos: [] },
      { day: 5, title: "Kasol to Manali", description: "Drive to Manali. Explore Old Manali and Mall Road.", photos: [] },
      { day: 6, title: "Manali Sightseeing", description: "Hadimba Temple, Jogini Waterfall, Vashisht.", photos: [] },
      { day: 7, title: "Solang Valley", description: "Adventure activities at Solang Valley. Atal Tunnel visit.", photos: [] },
      { day: 8, title: "Kullu Rafting & Return", description: "River rafting and start return journey.", photos: [] },
      { day: 9, title: "Arrival", description: "Reach back home.", photos: [] },
    ],
    heroImage: "",
    highlights: ["Guided tours", "Scenic views", "Group activities"],
    inclusions: ["Accommodation", "Meals (Breakfast & Dinner)", "Transport", "Sightseeing", "Trip captain"],
    exclusions: ["Personal expenses", "Travel insurance", "Entry fees (if any)", "Anything not mentioned in inclusions"],
    faqs: [
      { question: "What is the age limit?", answer: "This trip is suitable for ages 12-35." },
      { question: "Is food included?", answer: "Yes, breakfast and dinner are included." },
      { question: "What about safety?", answer: "We have trained trip captains and first-aid kits on every trip." },
    ],
    status: "published",
    createdAt: "2024-02-01",
    updatedAt: "2024-03-05",
  },
  {
    id: "3",
    title: "Winter Spiti Road Trip",
    slug: "winter-spiti-road-trip",
    description: "Spiti in winter is a world straight out of a postcard — blanketed in pristine white snow, frozen rivers, and towering Himalayan peaks.",
    price: 19999,
    location: "Spiti Valley, Himachal Pradesh",
    duration: "9 Nights 10 Days",
    category: "Road Trip",
    images: [
      "https://vl-prod-static.b-cdn.net/system/images/000/862/062/b7cb9dc7ccc9fe863f0f009c4fe1746f/x540gt/Website_Itinerary_Ohotos__2_.png",
      "https://vl-prod-static.b-cdn.net/system/images/000/862/060/5d50edec4e8decdefec9e352873b99e8/original/Website_Itinerary_Ohotos__4_.png",
      "https://vl-prod-static.b-cdn.net/system/images/000/862/061/9b72e8a2d0b5f7708ed73d1c712eed1a/original/Website_Itinerary_Ohotos__3_.png",
      "https://vl-prod-static.b-cdn.net/system/images/000/862/064/e80df5925dd74919f520937e2a6bda8f/original/Website_Itinerary_Ohotos.png",
    ],
    itinerary: [
      { day: 1, title: "Departure", description: "Overnight journey from Gujarat.", photos: [] },
      { day: 2, title: "Arrive Chandigarh/Shimla", description: "Rest and acclimatize.", photos: [] },
      { day: 3, title: "Shimla to Narkanda", description: "Drive through snow-covered roads to Narkanda.", photos: ["https://vl-prod-static.b-cdn.net/system/images/000/862/062/b7cb9dc7ccc9fe863f0f009c4fe1746f/x540gt/Website_Itinerary_Ohotos__2_.png"] },
      { day: 4, title: "Narkanda to Sangla", description: "Enter the Kinnaur Valley. Explore Sangla village.", photos: [] },
      { day: 5, title: "Sangla to Chitkul & Tabo", description: "Visit India's last village Chitkul, then drive to Tabo.", photos: [] },
      { day: 6, title: "Tabo to Kaza", description: "Explore Tabo monastery. Drive to Kaza, the heart of Spiti.", photos: ["https://vl-prod-static.b-cdn.net/system/images/000/862/060/5d50edec4e8decdefec9e352873b99e8/original/Website_Itinerary_Ohotos__4_.png"] },
      { day: 7, title: "Kaza Exploration", description: "Visit Hikkim, Komic, Langza, and Key Monastery.", photos: [] },
      { day: 8, title: "Kaza to Manali", description: "Drive through Kunzum Pass to Manali.", photos: [] },
      { day: 9, title: "Manali & Departure", description: "Explore Manali, begin return journey.", photos: [] },
      { day: 10, title: "Arrival", description: "Reach home.", photos: [] },
    ],
    heroImage: "",
    highlights: ["Guided tours", "Scenic views", "Group activities"],
    inclusions: ["Accommodation", "Meals (Breakfast & Dinner)", "Transport", "Sightseeing", "Trip captain"],
    exclusions: ["Personal expenses", "Travel insurance", "Entry fees (if any)", "Anything not mentioned in inclusions"],
    faqs: [
      { question: "What is the age limit?", answer: "This trip is suitable for ages 12-35." },
      { question: "Is food included?", answer: "Yes, breakfast and dinner are included." },
      { question: "What about safety?", answer: "We have trained trip captains and first-aid kits on every trip." },
    ],
    status: "published",
    createdAt: "2024-01-20",
    updatedAt: "2024-02-15",
  },
  {
    id: "4",
    title: "Spiti Valley Road Trip",
    slug: "spiti-valley-road-trip",
    description: "Experience an amazing journey through Himachal Pradesh! Explore quaint villages like Sangla, Chitkul, and Tabo.",
    price: 21499,
    location: "Sabarmati, Gujarat → Spiti Valley",
    duration: "10 Nights 11 Days",
    category: "Road Trip",
    images: [
      "https://vl-prod-static.b-cdn.net/system/images/000/751/384/13bebee8f5dfb67ee1756619de11e44a/x540gt/Untitled_design__50_.png",
      "https://vl-prod-static.b-cdn.net/system/images/000/751/383/f9e9b476346ed8ae84d29f5837f6e093/original/Untitled_design__51_.png",
      "https://vl-prod-static.b-cdn.net/system/images/000/751/385/0b859075c5accb9bb1decb348aa419ad/original/Untitled_design__49_.png",
      "https://vl-prod-static.b-cdn.net/system/images/000/751/386/a0218b14753015027900b134d4aa3a95/original/Untitled_design__48_.png",
    ],
    itinerary: [
      { day: 1, title: "Departure from Gujarat", description: "Overnight journey from Sabarmati.", photos: [] },
      { day: 2, title: "Arrive Chandigarh", description: "Sightseeing in Chandigarh.", photos: [] },
      { day: 3, title: "Chandigarh to Sangla", description: "Drive into the Kinnaur Valley.", photos: [] },
      { day: 4, title: "Sangla & Chitkul", description: "Explore Sangla and visit Chitkul.", photos: [] },
      { day: 5, title: "Chitkul to Tabo", description: "Drive to Tabo via Nako.", photos: [] },
      { day: 6, title: "Tabo to Kaza", description: "Explore Tabo Monastery. Arrive in Kaza.", photos: [] },
      { day: 7, title: "Kaza Sightseeing", description: "Hikkim, Komic, Langza, Key Monastery, Kibber.", photos: ["https://vl-prod-static.b-cdn.net/system/images/000/751/384/13bebee8f5dfb67ee1756619de11e44a/x540gt/Untitled_design__50_.png"] },
      { day: 8, title: "Kaza to Chandrataal", description: "Drive to the stunning Chandrataal Lake.", photos: [] },
      { day: 9, title: "Chandrataal to Manali", description: "Cross Kunzum Pass, arrive in Manali.", photos: [] },
      { day: 10, title: "Manali & Return", description: "Explore Manali, begin return.", photos: [] },
      { day: 11, title: "Arrival", description: "Reach home.", photos: [] },
    ],
    heroImage: "",
    highlights: ["Guided tours", "Scenic views", "Group activities"],
    inclusions: ["Accommodation", "Meals (Breakfast & Dinner)", "Transport", "Sightseeing", "Trip captain"],
    exclusions: ["Personal expenses", "Travel insurance", "Entry fees (if any)", "Anything not mentioned in inclusions"],
    faqs: [
      { question: "What is the age limit?", answer: "This trip is suitable for ages 12-35." },
      { question: "Is food included?", answer: "Yes, breakfast and dinner are included." },
      { question: "What about safety?", answer: "We have trained trip captains and first-aid kits on every trip." },
    ],
    status: "published",
    createdAt: "2024-02-10",
    updatedAt: "2024-03-01",
  },
  {
    id: "5",
    title: "Shimla Manali Dalhousie Dharamshala",
    slug: "shimla-manali-dalhousie-dharamshala",
    description: "A grand tour of Himachal Pradesh covering four iconic hill stations.",
    price: 16999,
    location: "Himachal Pradesh",
    duration: "9 Nights 10 Days",
    category: "Backpacking",
    images: [
      "https://vl-prod-static.b-cdn.net/system/images/000/856/207/68ae0d6c7bcc0a7716d1c860e7f2c58d/original/42294194395",
    ],
    itinerary: [
      { day: 1, title: "Departure", description: "Overnight journey.", photos: [] },
      { day: 2, title: "Arrive Shimla", description: "Explore Mall Road, Ridge, and Christ Church.", photos: [] },
      { day: 3, title: "Shimla to Manali", description: "Scenic drive to Manali.", photos: [] },
      { day: 4, title: "Manali Sightseeing", description: "Hadimba Temple, Solang Valley, Old Manali.", photos: [] },
      { day: 5, title: "Manali to Dharamshala", description: "Drive to Dharamshala.", photos: [] },
      { day: 6, title: "Dharamshala & McLeodganj", description: "Explore Tibetan culture, Bhagsu Waterfall, Namgyal Monastery.", photos: [] },
      { day: 7, title: "Dharamshala to Dalhousie", description: "Drive to Dalhousie.", photos: [] },
      { day: 8, title: "Dalhousie & Khajjiar", description: "Visit Khajjiar — the Mini Switzerland of India.", photos: [] },
      { day: 9, title: "Return Journey", description: "Begin return journey.", photos: [] },
      { day: 10, title: "Arrival", description: "Reach home.", photos: [] },
    ],
    heroImage: "",
    highlights: ["Guided tours", "Scenic views", "Group activities"],
    inclusions: ["Accommodation", "Meals (Breakfast & Dinner)", "Transport", "Sightseeing", "Trip captain"],
    exclusions: ["Personal expenses", "Travel insurance", "Entry fees (if any)", "Anything not mentioned in inclusions"],
    faqs: [
      { question: "What is the age limit?", answer: "This trip is suitable for ages 12-35." },
      { question: "Is food included?", answer: "Yes, breakfast and dinner are included." },
      { question: "What about safety?", answer: "We have trained trip captains and first-aid kits on every trip." },
    ],
    status: "published",
    createdAt: "2024-02-15",
    updatedAt: "2024-03-01",
  },
  {
    id: "6",
    title: "Kedarnath Tungnath & Rishikesh Trip",
    slug: "kedarnath-tungnath-rishikesh-backpacking-trip",
    description: "A spiritual and adventure-packed journey to the sacred Kedarnath Temple and the highest Shiva temple — Tungnath.",
    price: 16500,
    location: "Uttarakhand",
    duration: "5 Nights 6 Days",
    category: "Trekking",
    images: [
      "https://vl-prod-static.b-cdn.net/system/images/000/748/931/95ce9359f68bd2d93dee6aa2e3a18d17/x540gt/Untitled_design__11_.png",
    ],
    itinerary: [
      { day: 1, title: "Arrive Rishikesh", description: "Explore Laxman Jhula, Ram Jhula. Evening Ganga Aarti.", photos: [] },
      { day: 2, title: "Rishikesh to Chopta", description: "Drive to Chopta — the mini Switzerland of Uttarakhand.", photos: [] },
      { day: 3, title: "Tungnath & Chandrashila Trek", description: "Trek to Tungnath (highest Shiva temple) and Chandrashila summit.", photos: ["https://vl-prod-static.b-cdn.net/system/images/000/748/931/95ce9359f68bd2d93dee6aa2e3a18d17/x540gt/Untitled_design__11_.png"] },
      { day: 4, title: "Chopta to Kedarnath Base", description: "Drive to Sonprayag, begin Kedarnath trek.", photos: [] },
      { day: 5, title: "Kedarnath Temple", description: "Visit Kedarnath Temple. Trek back to base.", photos: [] },
      { day: 6, title: "Return to Rishikesh & Departure", description: "Rafting in Rishikesh, then departure.", photos: [] },
    ],
    heroImage: "",
    highlights: ["Guided tours", "Scenic views", "Group activities"],
    inclusions: ["Accommodation", "Meals (Breakfast & Dinner)", "Transport", "Sightseeing", "Trip captain"],
    exclusions: ["Personal expenses", "Travel insurance", "Entry fees (if any)", "Anything not mentioned in inclusions"],
    faqs: [
      { question: "What is the age limit?", answer: "This trip is suitable for ages 12-35." },
      { question: "Is food included?", answer: "Yes, breakfast and dinner are included." },
      { question: "What about safety?", answer: "We have trained trip captains and first-aid kits on every trip." },
    ],
    status: "published",
    createdAt: "2024-01-10",
    updatedAt: "2024-02-20",
  },
  {
    id: "7",
    title: "Kedarnath Badrinath - Tungnath & Rishikesh",
    slug: "kedarnath-badrinath-tungnath-rishikesh",
    description: "Kedarnath Temple stands at 3,580 meters in the Garhwal Himalayas and is one of the twelve Jyotirlingas of Lord Shiva.",
    price: 19499,
    location: "Uttarakhand",
    duration: "8 Nights 7 Days",
    category: "Pilgrimage",
    images: [
      "https://vl-prod-static.b-cdn.net/system/images/000/748/925/95ce9359f68bd2d93dee6aa2e3a18d17/x540gt/Untitled_design__11_.png",
      "https://vl-prod-static.b-cdn.net/system/images/000/748/920/5abeca5343adce67a22013a929647f71/original/Untitled_design__12_.png",
      "https://vl-prod-static.b-cdn.net/system/images/000/748/921/30e9ea2cafbd0b433acdf1c21b6d3e0c/original/Untitled_design__13_.png",
      "https://vl-prod-static.b-cdn.net/system/images/000/748/922/075d7fdc9ae72490c7c886bf84576cf6/original/Untitled_design__17_.png",
    ],
    itinerary: [
      { day: 1, title: "Arrive Rishikesh", description: "Check in, explore Rishikesh.", photos: [] },
      { day: 2, title: "Rishikesh to Chopta", description: "Drive to Chopta.", photos: [] },
      { day: 3, title: "Tungnath Trek", description: "Trek to Tungnath and Chandrashila Peak.", photos: [] },
      { day: 4, title: "Chopta to Kedarnath Base", description: "Drive to Sonprayag. Begin Kedarnath trek.", photos: [] },
      { day: 5, title: "Kedarnath Temple", description: "Darshan at Kedarnath Temple. Trek back.", photos: ["https://vl-prod-static.b-cdn.net/system/images/000/748/920/5abeca5343adce67a22013a929647f71/original/Untitled_design__12_.png"] },
      { day: 6, title: "Travel to Badrinath", description: "Drive to Badrinath. Visit Mana Village.", photos: [] },
      { day: 7, title: "Badrinath Temple & Return", description: "Morning darshan at Badrinath. Drive back to Rishikesh.", photos: ["https://vl-prod-static.b-cdn.net/system/images/000/748/921/30e9ea2cafbd0b433acdf1c21b6d3e0c/original/Untitled_design__13_.png"] },
      { day: 8, title: "Departure", description: "Rafting in Rishikesh, then departure.", photos: [] },
    ],
    heroImage: "",
    highlights: ["Guided tours", "Scenic views", "Group activities"],
    inclusions: ["Accommodation", "Meals (Breakfast & Dinner)", "Transport", "Sightseeing", "Trip captain"],
    exclusions: ["Personal expenses", "Travel insurance", "Entry fees (if any)", "Anything not mentioned in inclusions"],
    faqs: [
      { question: "What is the age limit?", answer: "This trip is suitable for ages 12-35." },
      { question: "Is food included?", answer: "Yes, breakfast and dinner are included." },
      { question: "What about safety?", answer: "We have trained trip captains and first-aid kits on every trip." },
    ],
    status: "published",
    createdAt: "2024-02-01",
    updatedAt: "2024-02-28",
  },
  {
    id: "8",
    title: "Shimla Manali Kullu",
    slug: "shimla-manali-kullu",
    description: "Explore the best of Himachal Pradesh with this classic trip covering Shimla, Manali, and Kullu.",
    price: 12999,
    location: "Shimla, Himachal Pradesh",
    duration: "7 Nights 8 Days",
    category: "Backpacking",
    images: [
      "https://vl-prod-static.b-cdn.net/system/images/000/795/284/3bba832671671da87e0f23ce9864e6c1/x540gt/27121997__26_.jpg",
    ],
    itinerary: [
      { day: 1, title: "Departure", description: "Overnight journey from Gujarat.", photos: [] },
      { day: 2, title: "Arrive Shimla", description: "Explore Mall Road, Ridge, Jakhu Temple.", photos: [] },
      { day: 3, title: "Shimla Sightseeing", description: "Kufri, Green Valley, Indian Institute of Advanced Study.", photos: [] },
      { day: 4, title: "Shimla to Manali", description: "Scenic drive to Manali.", photos: [] },
      { day: 5, title: "Manali Exploration", description: "Hadimba Temple, Vashisht, Old Manali.", photos: [] },
      { day: 6, title: "Solang Valley & Atal Tunnel", description: "Adventure at Solang, visit Atal Tunnel.", photos: [] },
      { day: 7, title: "Kullu Rafting & Return", description: "River rafting in Kullu. Begin return.", photos: [] },
      { day: 8, title: "Arrival", description: "Reach home.", photos: [] },
    ],
    heroImage: "",
    highlights: ["Guided tours", "Scenic views", "Group activities"],
    inclusions: ["Accommodation", "Meals (Breakfast & Dinner)", "Transport", "Sightseeing", "Trip captain"],
    exclusions: ["Personal expenses", "Travel insurance", "Entry fees (if any)", "Anything not mentioned in inclusions"],
    faqs: [
      { question: "What is the age limit?", answer: "This trip is suitable for ages 12-35." },
      { question: "Is food included?", answer: "Yes, breakfast and dinner are included." },
      { question: "What about safety?", answer: "We have trained trip captains and first-aid kits on every trip." },
    ],
    status: "published",
    createdAt: "2024-01-25",
    updatedAt: "2024-02-15",
  },
  {
    id: "9",
    title: "Leh Ladakh Bike Expedition 2026",
    slug: "leh-ladakh-bike-expedition-2026",
    description: "Experience the raw beauty of the Himalayas on this thrilling adventure through the heart of Ladakh.",
    price: 18999,
    location: "Leh, Ladakh",
    duration: "6 Nights 7 Days",
    category: "Bike Expedition",
    images: [
      "https://vl-prod-static.b-cdn.net/system/images/000/888/077/e84148f8d1adacaa5dc96e8f834b8cdd/x540gt/t2-graphy-IJfpVYlRv5I-unsplash.jpg",
      "https://vl-prod-static.b-cdn.net/system/images/000/888/133/bae231ef3cdd69e7dc0d467e3ba04cbe/original/Website_Itinerary_Ohotos__4_.jpg",
      "https://vl-prod-static.b-cdn.net/system/images/000/888/134/10b5d1ede53e33bb93e210e4846fcec9/original/Website_Itinerary_Ohotos__3_.jpg",
      "https://vl-prod-static.b-cdn.net/system/images/000/888/135/4aa2a2c0426f7d3274b80929e939eec6/original/Website_Itinerary_Ohotos__2_.jpg",
    ],
    itinerary: [
      { day: 1, title: "Arrive Leh", description: "Fly to Leh. Rest and acclimatize. Explore Leh Market.", photos: [] },
      { day: 2, title: "Leh Sightseeing", description: "Visit Shanti Stupa, Leh Palace, Hall of Fame, Magnetic Hill.", photos: [] },
      { day: 3, title: "Leh to Nubra Valley", description: "Ride over Khardung La Pass (17,982 ft). Explore Diskit Monastery and Hunder sand dunes.", photos: ["https://vl-prod-static.b-cdn.net/system/images/000/888/133/bae231ef3cdd69e7dc0d467e3ba04cbe/original/Website_Itinerary_Ohotos__4_.jpg"] },
      { day: 4, title: "Nubra to Turtuk", description: "Visit the charming border village of Turtuk.", photos: [] },
      { day: 5, title: "Turtuk to Pangong Lake", description: "Ride to the stunning Pangong Tso Lake.", photos: ["https://vl-prod-static.b-cdn.net/system/images/000/888/134/10b5d1ede53e33bb93e210e4846fcec9/original/Website_Itinerary_Ohotos__3_.jpg"] },
      { day: 6, title: "Pangong to Leh", description: "Drive back to Leh via Chang La Pass.", photos: [] },
      { day: 7, title: "Departure", description: "Fly out from Leh.", photos: [] },
    ],
    heroImage: "",
    highlights: ["Guided tours", "Scenic views", "Group activities"],
    inclusions: ["Accommodation", "Meals (Breakfast & Dinner)", "Transport", "Sightseeing", "Trip captain"],
    exclusions: ["Personal expenses", "Travel insurance", "Entry fees (if any)", "Anything not mentioned in inclusions"],
    faqs: [
      { question: "What is the age limit?", answer: "This trip is suitable for ages 12-35." },
      { question: "Is food included?", answer: "Yes, breakfast and dinner are included." },
      { question: "What about safety?", answer: "We have trained trip captains and first-aid kits on every trip." },
    ],
    status: "published",
    createdAt: "2024-03-01",
    updatedAt: "2024-03-10",
  },
];
export const mockBookings: Booking[] = [
  { id: "b1", userName: "Rahul Patel", email: "rahul.patel@gmail.com", phone: "+91 98765 43210", tripId: "1", tripTitle: "Manali Kasol Amritsar Backpacking Trip", status: "confirmed", amount: 11999, createdAt: "2024-03-01" },
  { id: "b2", userName: "Priya Sharma", email: "priya.sharma@gmail.com", phone: "+91 87654 32109", tripId: "3", tripTitle: "Winter Spiti Road Trip", status: "pending", amount: 19999, createdAt: "2024-03-05" },
  { id: "b3", userName: "Arjun Mehta", email: "arjun.m@gmail.com", phone: "+91 99887 76655", tripId: "9", tripTitle: "Leh Ladakh Bike Expedition 2026", status: "confirmed", amount: 18999, createdAt: "2024-03-08" },
  { id: "b4", userName: "Sneha Desai", email: "sneha.d@gmail.com", phone: "+91 77665 54433", tripId: "4", tripTitle: "Spiti Valley Road Trip", status: "cancelled", amount: 21499, createdAt: "2024-03-10" },
  { id: "b5", userName: "Karan Singh", email: "karan.singh@gmail.com", phone: "+91 88776 65544", tripId: "7", tripTitle: "Kedarnath Badrinath - Tungnath & Rishikesh", status: "pending", amount: 19499, createdAt: "2024-03-12" },
  { id: "b6", userName: "Ananya Joshi", email: "ananya.j@gmail.com", phone: "+91 66554 43322", tripId: "5", tripTitle: "Shimla Manali Dalhousie Dharamshala", status: "confirmed", amount: 16999, createdAt: "2024-03-15" },
  { id: "b7", userName: "Vikram Rathod", email: "vikram.r@gmail.com", phone: "+91 95432 10987", tripId: "8", tripTitle: "Shimla Manali Kullu", status: "confirmed", amount: 12999, createdAt: "2024-03-18" },
  { id: "b8", userName: "Meera Nair", email: "meera.nair@gmail.com", phone: "+91 91234 56789", tripId: "6", tripTitle: "Kedarnath Tungnath & Rishikesh Trip", status: "pending", amount: 16500, createdAt: "2024-03-20" },
];

export const mockInquiries: Inquiry[] = [
  { id: "i1", name: "Amit Shah", email: "amit.s@gmail.com", phone: "+91 98765 11111", message: "I'm interested in the Leh Ladakh Bike Expedition. Do I need my own bike or do you provide Royal Enfields? Also, is prior riding experience required?", tripTitle: "Leh Ladakh Bike Expedition 2026", read: false, createdAt: "2024-03-14" },
  { id: "i2", name: "Divya Patel", email: "divya.p@gmail.com", phone: "+91 87654 22222", message: "Can you customize the Spiti Valley trip for a group of 8 friends? We'd prefer private transport instead of shared. What would be the cost difference?", tripTitle: "Spiti Valley Road Trip", read: true, createdAt: "2024-03-12" },
  { id: "i3", name: "Rohan Gupta", email: "rohan.g@gmail.com", phone: "+91 99887 33333", message: "Is the Kedarnath trek suitable for beginners? My fitness level is average. Also what's the minimum age requirement?", tripTitle: "Kedarnath Tungnath & Rishikesh Trip", read: false, createdAt: "2024-03-10" },
  { id: "i4", name: "Nisha Verma", email: "nisha.v@gmail.com", phone: "+91 77665 44444", message: "Do you have any trips planned for Rajasthan or Goa? I'm looking for a beach + heritage combo trip for December.", read: true, createdAt: "2024-03-08" },
  { id: "i5", name: "Jay Thakor", email: "jay.t@gmail.com", phone: "+91 92345 67890", message: "I booked the Manali Kasol trip for April batch. Can I add the Kullu rafting addon? Also, can my 11-year-old brother join?", tripTitle: "Manali Kasol Amritsar Backpacking Trip", read: false, createdAt: "2024-03-16" },
];

export const mockMedia: MediaItem[] = [
  { id: "m1", url: "https://vl-prod-static.b-cdn.net/system/images/000/888/076/6f012c2f939c45fd491d86b3d33b0cbb/x540gt/IMG_3309.jpg", name: "manali-kasol-cover.jpg", size: 245000, type: "image/jpeg", createdAt: "2024-03-01" },
  { id: "m2", url: "https://vl-prod-static.b-cdn.net/system/images/000/862/062/b7cb9dc7ccc9fe863f0f009c4fe1746f/x540gt/Website_Itinerary_Ohotos__2_.png", name: "winter-spiti-cover.png", size: 312000, type: "image/png", createdAt: "2024-03-02" },
  { id: "m3", url: "https://vl-prod-static.b-cdn.net/system/images/000/748/925/95ce9359f68bd2d93dee6aa2e3a18d17/x540gt/Untitled_design__11_.png", name: "kedarnath-cover.png", size: 198000, type: "image/png", createdAt: "2024-03-03" },
  { id: "m4", url: "https://vl-prod-static.b-cdn.net/system/images/000/888/077/e84148f8d1adacaa5dc96e8f834b8cdd/x540gt/t2-graphy-IJfpVYlRv5I-unsplash.jpg", name: "leh-ladakh-cover.jpg", size: 278000, type: "image/jpeg", createdAt: "2024-03-04" },
  { id: "m5", url: "https://vl-prod-static.b-cdn.net/system/images/000/751/384/13bebee8f5dfb67ee1756619de11e44a/x540gt/Untitled_design__50_.png", name: "spiti-valley-cover.png", size: 356000, type: "image/png", createdAt: "2024-03-05" },
  { id: "m6", url: "https://vl-prod-static.b-cdn.net/system/images/000/856/207/68ae0d6c7bcc0a7716d1c860e7f2c58d/original/42294194395", name: "shimla-dalhousie-cover.jpg", size: 289000, type: "image/jpeg", createdAt: "2024-03-06" },
  { id: "m7", url: "https://vl-prod-static.b-cdn.net/system/images/000/795/284/3bba832671671da87e0f23ce9864e6c1/x540gt/27121997__26_.jpg", name: "shimla-manali-kullu.jpg", size: 220000, type: "image/jpeg", createdAt: "2024-03-07" },
  { id: "m8", url: "https://vl-prod-static.b-cdn.net/system/images/000/748/614/9b56160b1abe219a402c11001702ae24/x540gt/IMG_3398.JPG", name: "manali-kasol-summer.jpg", size: 195000, type: "image/jpeg", createdAt: "2024-03-08" },
  { id: "m9", url: "https://vl-prod-static.b-cdn.net/system/images/000/753/039/8d7697334dd13b947df57a1469df94d2/x110gt/IMG_6911.png", name: "youthcamping-logo.png", size: 45000, type: "image/png", createdAt: "2024-01-01" },
  { id: "m10", url: "https://vl-prod-static.b-cdn.net/system/images/000/780/691/c436acb230aef2966afeac73a90aa076/original/Purple_Illustration_City_Desktop_Wallpaper.jpg", name: "hero-banner.jpg", size: 410000, type: "image/jpeg", createdAt: "2024-01-15" },
];

const totalRevenue = mockBookings.reduce((sum, b) => b.status !== "cancelled" ? sum + b.amount : sum, 0);

export const mockDashboardStats: DashboardStats = {
  totalTrips: mockTrips.length,
  totalBookings: mockBookings.length,
  totalRevenue: totalRevenue,
  totalInquiries: mockInquiries.length,
  recentBookings: mockBookings.slice(0, 5),
  monthlyRevenue: [
    { month: "Jan", revenue: 45997 },
    { month: "Feb", revenue: 62498 },
    { month: "Mar", revenue: 89995 },
    { month: "Apr", revenue: 105493 },
    { month: "May", revenue: 134991 },
    { month: "Jun", revenue: totalRevenue },
  ],
  bookingsByStatus: [
    { status: "Confirmed", count: mockBookings.filter((b) => b.status === "confirmed").length },
    { status: "Pending", count: mockBookings.filter((b) => b.status === "pending").length },
    { status: "Cancelled", count: mockBookings.filter((b) => b.status === "cancelled").length },
  ],
};

export const mockSettings: SiteSettings = {
  siteName: "YouthCamping",
  contactEmail: "youthcampingmedia@gmail.com",
  contactPhone: "+91 99242 46267",
  address: "Gujarat, India",
  currency: "INR",
  paymentGateway: "razorpay",
};
